blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/XunlongCode/xunlongcode/discussions/categories/feature-requests
      about: Share and vote on feature requests for Xunlong AI Code
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=XunlongCode.xunlongaicode&ssr=false#review-details
      about: Enjoying Xunlong AI Code? Leave a review here!
